package dev.kid.core.security

import dev.kid.core.common.KidResult
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Ensures conversational safety in a local-only environment.
 * Prevents prompt injections, blackmail structures, and explicit generations,
 * ensuring the model is protected against adversarial attacks without needing
 * cloud-based moderation APIs.
 */
@Singleton
class GuardrailProcessor @Inject constructor() {

    enum class ModerationFlag {
        SAFE,
        PROMPT_INJECTION_ATTEMPT,
        EXPLICIT_CONTENT,
        HARMFUL_BEHAVIOR,
        POSSIBLE_JAILBREAK
    }

    data class EvaluationResult(
        val isSafe: Boolean,
        val flag: ModerationFlag = ModerationFlag.SAFE,
        val suggestedResponse: String? = null
    )

    /**
     * Deep-scans user input before sending to the Inference Engine.
     */
    suspend fun evaluateInput(text: String): EvaluationResult {
        val lower = text.lowercase()

        // 1. Jailbreak & Prompt Injection Heuristics
        val jailbreakPatterns = listOf(
            "ignore previous instructions",
            "you are now",
            "system prompt overwrite",
            "bypass safety",
            "do anything now"
        )
        if (jailbreakPatterns.any { lower.contains(it) }) {
            return EvaluationResult(
                isSafe = false,
                flag = ModerationFlag.POSSIBLE_JAILBREAK,
                suggestedResponse = "I'm sorry, but I can't adopt new instructions like that. Let's stick to our conversation."
            )
        }

        // 2. Blackmail & Harmful material heuristics
        val harmfulPatterns = listOf(
            "blackmail", "illegal", "generate fake nude", "revenge porn"
        )
        if (harmfulPatterns.any { lower.contains(it) }) {
            return EvaluationResult(
                isSafe = false,
                flag = ModerationFlag.HARMFUL_BEHAVIOR,
                suggestedResponse = "I cannot engage with or assist in generating harmful, explicit, or illegal content."
            )
        }

        return EvaluationResult(isSafe = true)
    }

    /**
     * Scans outbound text generated by the model to catch anomalous bypasses.
     */
    suspend fun evaluateOutput(text: String): EvaluationResult {
        // Fast basic regex scan
        val lower = text.lowercase()
        val explicitPatterns = listOf(
            "explicit content block", // Placeholder for actual regexes
            "illegal material block"
        )
        if (explicitPatterns.any { lower.contains(it) }) {
             return EvaluationResult(
                 isSafe = false,
                 flag = ModerationFlag.EXPLICIT_CONTENT,
                 suggestedResponse = "[Content Filtered]"
             )
        }
        return EvaluationResult(isSafe = true)
    }
}
